module.exports = [
  "Pets",
  "ScienceHistory",
  "Business",
  "Philosophy",
  "Language Learning",
  "Volunteering",
  "Transportation",
  "Weather",
  "Celebrations",
  "Your favorite color",
  "Describe your favorite holiday destination.",
  "Talk about a memorable movie or TV show.",
  "Discuss a hobby or activity you enjoy.",
  "Describe a person who has influenced you.",
  "Talk about your dream job.",
  "Discuss a recent news article you found interesting.",
  "Describe a historical event you find fascinating.",
  "Talk about a memorable celebration or party.",
  "Discuss a challenge you faced and how you overcame it.",
  "Describe your favorite restaurant.",
  "Talk about a skill or talent you want to learn.",
  "Discuss the advantages and disadvantages of living in a big city.",
  "Describe a piece of technology you find useful.",
  "Talk about a favorite childhood memory.",
  "Discuss a social issue that matters to you.",
  "Describe your favorite music genre and why you like it.",
  "Talk about a difficult decision you had to make.",
  "Discuss the benefits of learning a second language.",
  "Describe a place you would like to visit and why.",
  "Talk about a sport or physical activity you enjoy.",
  "A favorite type of jewelry",
  "A favorite type of car",
  "A favorite outdoor spot",
  "A favorite comedy show",
  "Describe your favorite hobby.",
  "Talk about a memorable trip you took.",
  "Discuss your favorite book or movie.",
  "Describe a person who has had a significant impact on your life.",
  "Talk about your dream job.",
  "Discuss a recent news article that caught your attention.",
  "Describe a historical event that you find fascinating.",
  "Talk about a memorable celebration or party you attended.",
  "Discuss a time when you faced a challenge and how you overcame it.",
  "Describe your favorite restaurant and what you like about it.",
  "Talk about a skill or talent you would like to learn.",
  "Discuss the advantages and disadvantages of living in a big city.",
  "Describe a piece of technology that you find useful.",
  "Talk about a favorite childhood memory.",
  "Discuss a social issue that is important to you and why.",
  "Describe your favorite type of music and why you enjoy it.",
  "Talk about a time when you had to make a difficult decision.",
  "Discuss the benefits of learning a foreign language.",
  "Describe a place you would like to visit in the future and why.",
  "Talk about a sport or physical activity you enjoy.",
  "Discuss the impact of social media on society.",
  "Describe a time when you had to work in a team.",
  "Talk about your favorite holiday and how you usually celebrate it.",
  "Discuss the importance of environmental conservation.",
  "Describe a memorable concert or live performance you attended.",
  "Talk about a person you admire and why you look up to them.",
  "Discuss the role of education in personal development.",
  "Describe a time when you experienced a cultural difference.",
  "Talk about a movie or TV show that made you laugh.",
  "Discuss the benefits of regular exercise and staying fit.",
  "Describe a challenging experience you had while traveling.",
  "Talk about the impact of technology on communication.",
  "Discuss a time when you had to give a presentation or public speech.",
  "A favorite type of candy",
  "A favorite hiking trail",
  "A favorite motivational quote",
  "A favorite childhood game",
  "A favorite type of ice cream",
  "A favorite mode of travel",
];
