module.exports = [
  "Family traditions",
  "Favorite holiday destination",
  "Dream job",
  "Hobbies and interests",
  "Favorite book or movie",
  "Travel experiences",
  "Daily routines",
  "Memorable childhood event",
  "Environmental issues",
  "Technology advancements",
  "Favorite food",
  "Sports and fitness",
  "Music preferences",
  "Celebrity culture",
  "Education system",
  "Future aspirations",
  "Social media impact",
  "Cultural festivals",
  "Healthy lifestyle choices",
  "Global warming",
  "Art and creativity",
  "Personal achievements",
  "Fashion and style",
  "Volunteering experiences",
  "Time management",
  "Role models",
  "The influence of advertisements",
  "Relationships and dating",
  "Language learning experiences",
  "Challenges faced in life",
  "Favorite TV shows",
  "The impact of technology on communication",
  "Career choices",
  "Friendships",
  "Inequality and discrimination",
  "Cinema and film industry",
  "Leisure activities",
  "Traditional vs. modern values",
  "Effects of globalization",
  "Healthcare system",
  "Climate change",
  "Entrepreneurship",
  "The role of government",
  "Childhood memories",
  "Importance of reading",
  "Impact of social media on society",
  "Advantages and disadvantages of online shopping",
  "Stress management techniques",
  "Importance of cultural diversity",
  "Influence of music on emotions",
  "Benefits of physical exercise",
  "Dream travel destinations",
  "Innovation and technology",
  "Effects of fast food on health",
  "Importance of financial literacy",
  "Censorship in the media",
  "Importance of higher education",
  "The role of art in society",
  "The influence of celebrities on young people",
  "Impact of video games on youth",
  "Benefits of multicultural societies",
  "Role of traditional gender roles",
  "The concept of beauty",
  "Importance of learning multiple languages",
  "Positive and negative aspects of social networking",
  "Impacts of urbanization",
  "Role of government in environmental protection",
  "Benefits of team sports",
  "Importance of mental health awareness",
  "The significance of cultural heritage",
  "Impacts of artificial intelligence",
  "Benefits of lifelong learning",
  "Influence of advertising on children",
  "Importance of time management skills",
  "Impact of tourism on local communities",
  "The role of teachers in students' lives",
  "Benefits of volunteer work",
  "Importance of early childhood education",
  "Effects of climate change on the environment",
  "Influence of pop culture on society",
  "Advantages and disadvantages of online learning",
  "Importance of work-life balance",
  "Impacts of online privacy",
  "Benefits of meditation and mindfulness",
  "Influence of mass media on society",
  "Challenges of globalization",
  "Importance of cultural exchange programs",
  "Impact of social media on self-esteem",
  "The role of parents in child development",
  "Benefits of renewable energy",
  "Importance of critical thinking skills",
  "Effects of consumerism on society",
]