// topic 数组，根据名字确定index用来做数据缓存
module.exports = [
  "Family traditions",
  "Favorite holiday destination",
  "Dream job",
  "Hobbies and interests",
  "Favorite book or movie",
  "Travel experiences",
  "Daily routines",
  "Memorable childhood event",
  "Environmental issues",
  "Technology advancements",
  "Favorite food",
  "Sports and fitness",
  "Music preferences",
  "Celebrity culture",
  "Education system",
  "Future aspirations",
  "Social media impact",
  "Cultural festivals",
  "Healthy lifestyle choices",
  "Global warming",
  "Art and creativity",
  "Personal achievements",
  "Fashion and style",
  "Volunteering experiences",
  "Time management",
  "Role models",
  "The influence of advertisements",
  "Relationships and dating",
  "Language learning experiences",
  "Challenges faced in life",
  "Favorite TV shows",
  "The impact of technology on communication",
  "Career choices",
  "Friendships",
  "Inequality and discrimination",
  "Cinema and film industry",
  "Leisure activities",
  "Traditional vs. modern values",
  "Effects of globalization",
  "Healthcare system",
  "Climate change",
  "Entrepreneurship",
  "The role of government",
  "Childhood memories",
  "Importance of reading",
  "Impact of social media on society",
  "Advantages and disadvantages of online shopping",
  "Stress management techniques",
  "Importance of cultural diversity",
  "Influence of music on emotions",
  "Benefits of physical exercise",
  "Dream travel destinations",
  "Innovation and technology",
  "Effects of fast food on health",
  "Importance of financial literacy",
  "Censorship in the media",
  "Importance of higher education",
  "The role of art in society",
  "The influence of celebrities on young people",
  "Impact of video games on youth",
  "Benefits of multicultural societies",
  "Role of traditional gender roles",
  "The concept of beauty",
  "Importance of learning multiple languages",
  "Positive and negative aspects of social networking",
  "Impacts of urbanization",
  "Role of government in environmental protection",
  "Benefits of team sports",
  "Importance of mental health awareness",
  "The significance of cultural heritage",
  "Impacts of artificial intelligence",
  "Benefits of lifelong learning",
  "Influence of advertising on children",
  "Importance of time management skills",
  "Impact of tourism on local communities",
  "The role of teachers in students' lives",
  "Benefits of volunteer work",
  "Importance of early childhood education",
  "Effects of climate change on the environment",
  "Influence of pop culture on society",
  "Advantages and disadvantages of online learning",
  "Importance of work-life balance",
  "Impacts of online privacy",
  "Benefits of meditation and mindfulness",
  "Influence of mass media on society",
  "Challenges of globalization",
  "Importance of cultural exchange programs",
  "Impact of social media on self-esteem",
  "The role of parents in child development",
  "Benefits of renewable energy",
  "Importance of critical thinking skills",
  "Effects of consumerism on society","Influence of fashion on youth",
  "Role of sports in society",
  "The significance of historical landmarks",
  "Impacts of automation on employment",
  "Benefits of a healthy diet",
  "Importance of community involvement",
  "Effects of online dating on relationships",
  "Influence of advertising on consumer behavior",
  "Role of technology in education",
  "Importance of cultural tolerance",
  "Impact of social media on political activism",
  "Benefits of learning a musical instrument",
  "The concept of success",
  "Impacts of deforestation on the environment",
  "Importance of teamwork skills",
  "Effects of population growth on resources",
  "Influence of celebrities on fashion trends",
  "Role of media in shaping public opinion",
  "The significance of historical events",
  "Impacts of genetic engineering",
  "Benefits of a positive mindset",
  "Importance of ethics in business",
  "Effects of overpopulation on society",
  "Influence of technology on privacy",
  "Role of education in social equality",
  "The concept of freedom",
  "Impacts of consumer culture",
  "Benefits of cultural exchange",
  "Importance of digital literacy",
  "Effects of air pollution on health",
  "Influence of social norms on behavior",
  "Role of arts education in schools",
  "The significance of scientific discoveries",
  "Impacts of space exploration",
  "Benefits of learning through travel",
  "Importance of effective communication skills",
  "Effects of income inequality",
  "Influence of media on body image",
  "Role of government in public health",
  "The concept of justice",
  "Impacts of plastic pollution on the environment",
  "Benefits of learning about different cultures",
  "Importance of personal branding",
  "Effects of urban sprawl",
  "Influence of technology on relationships",
  "Role of music in therapy",
  "The significance of cultural celebrations",
  "Impacts of artificial intelligence on employment",
  "Benefits of lifelong friendships",
  "Importance of empathy and compassion",
  "Effects of noise pollution on health",
  "Influence of social media influencers",
  "Role of creativity in problem-solving",
  "The concept of equality",
  "Impacts of water pollution on ecosystems",
  "Benefits of intercultural marriages",
  "Importance of continuous professional development",
  "Effects of mass tourism on the environment",
  "Influence of advertising on children's behavior",
  "Role of technology in environmental conservation",
  "The significance of ancient civilizations",
  "Impacts of renewable energy on the economy",
  "Benefits of outdoor activities",
  "Importance of cultural preservation",
  "Effects of fast fashion on the environment",
  "Influence of social media on mental health",
  "Role of art in therapy",
  "The concept of democracy",
  "Impacts of marine pollution on marine life",
  "Benefits of learning a second language",
  "Importance of emotional intelligence",
  "Effects of noise pollution on wildlife",
  "Influence of social media on political campaigns",
  "Role of creativity in education",
  "The significance of historical documents",
  "Impacts of deforestation on indigenous communities",
  "Benefits of cultural diversity in the workplace",
  "Importance of financial management skills",
  "Effects of soil erosion on agriculture",
  "Influence of advertising on body image",
  "Role of technology in disaster management",
  "The concept of identity",
  "Impacts of air pollution on climate change",
  "Benefits of intercultural communication",
  "Importance of leadership skills",
  "Effects of light pollution on ecosystems",
  "Influence of social media on youth activism",
  "Role of arts in cultural expression",
  "The significance of archaeological discoveries",
  "Impacts of nuclear energy on the environment",
  "Benefits of cultural appreciation",
  "Importance of conflict resolution skills",
  "Effects of water scarcity on communities",
  "Influence of media on stereotypes",
  "Role of technology in healthcare",
  "The concept of tolerance",
  "Impacts of deforestation on indigenous cultures",
  "Benefits of multicultural education",
  "Importance of adaptability in the workplace",
  "Effects of noise pollution on sleep",
  "Influence of social media on body positivity",
  "Role of music in social movements",
  "The significance of cultural landmarks",
  "Impacts of fossil fuel consumption",
  "Benefits of intercultural friendships",
  "Importance of ethical decision-making",
  "Effects of land degradation on food security",
  "Influence of advertising on consumer choices",
  "Role of technology in social justice",
  "The concept of human rights",
  "Impacts of water scarcity on global conflicts",
  "Benefits of cross-cultural collaboration",
  "Importance of problem-solving skills",
  "Effects of light pollution on human health",
  "Influence of media on political opinions",
  "Role of art in cultural identity",
  "The significance of ancient ruins",
  "Impacts of renewable energy on job creation",
  "Benefits of studying abroad",
  "Importance of effective teamwork",
  "Effects of deforestation on wildlife habitats",
  "Influence of advertising on materialism",
  "Role of technology in environmental education",
  "The concept of cultural assimilation",
  "Impacts of air pollution on respiratory health",
  "Benefits of intercultural understanding",
  "Importance of digital communication skills",
  "Effects of plastic pollution on marine life",
  "Influence of social media on self-expression",
  "Role of music in cultural preservation",
  "The significance of historical figures",
  "Impacts of sustainable agriculture",
  "Benefits of intercultural competence",
  "Importance of negotiation skills",
  "Effects of water pollution on aquatic ecosystems",
  "Influence of media on political awareness",
  "Role of technology in environmental monitoring",
  "The concept of social equality",
  "Impacts of deforestation on climate change",
  "Benefits of studying different cultures",
  "Importance of active listening skills",
  "Effects of air pollution on wildlife",
  "Influence of social media on societal norms",
  "Role of music in emotional well-being",
  "The significance of cultural museums",
  "Impacts of renewable energy on energy security",
  "Benefits of cultural immersion",
  "Importance of effective presentation skills",
  "Effects of deforestation on indigenous species",
  "Influence of advertising on children's values",
  "Role of technology in sustainable cities",
  "The concept of cultural diversity",
  "Impacts of water pollution on public health",
  "Benefits of intercultural experiences",
  "Importance of critical listening skills",
  "Effects of noise pollution on cognitive performance",
  "Influence of social media on online activism",
  "Role of arts in social change",
  "The significance of historical artifacts",
  "Impacts of sustainable tourism",
  "Benefits of intercultural communication in business",
  "Importance of cross-cultural leadership skills",
  "Effects of land pollution on ecosystems",
  "Influence of advertising on body dissatisfaction",
  "Role of technology in disaster relief efforts",
  "The concept of cultural identity",
  "Impacts of air pollution on human health",
  "Benefits of cultural exchange programs",
  "Importance of effective negotiation skills",
  "Effects of water scarcity on agriculture",
  "Influence of media on consumer behavior",
  "Role of art in promoting social justice",
  "The significance of cultural traditions",
  "Impacts of renewable energy on economic growth",
  "Benefits of studying different religions",
  "Importance of cultural awareness in healthcare",
  "Effects of deforestation on water resources",
  "Influence of advertising on self-esteem",
  "Role of technology in disaster preparedness",
  "The concept of cultural stereotypes",
  "Impacts of noise pollution on human well-being",
  "Benefits of cross-cultural friendships",
  "Importance of effective communication in relationships",
  "Effects of plastic pollution on land ecosystems",
  "Influence of social media on mental well-being",
  "Role of music in promoting cultural understanding",
  "The significance of historical literature",
  "Impacts of sustainable transportation",
  "Benefits of intercultural teamwork",
  "Importance of cultural sensitivity in the workplace",
  "Effects of air pollution on climate patterns",
  "Influence of media on cultural values",
  "Role of technology in promoting accessibility",
  "The concept of cultural preservation",
  "Impacts of water pollution on fish populations",
  "Benefits of studying world history",
  "Importance of intercultural communication in tourism",
  "Effects of deforestation on soil erosion",
  "Influence of advertising on consumer trust",
  "Role of technology in disaster recovery",
  "The significance of cultural diversity in education",
  "Impacts of noise pollution on urban environments",
  "Benefits of intercultural relationships",
  "Importance of cultural intelligence in the workplace",
  "Effects of plastic pollution on wildlife conservation",
  "Influence of social media on political participation",
  "Role of arts in fostering cultural appreciation",
  "The concept of cultural integration",
  "Impacts of air pollution on ecosystems",
  "Benefits of intercultural festivals",
  "Importance of intercultural competence in healthcare",
  "Effects of water scarcity on biodiversity",
  "Influence of advertising on consumer satisfaction",
  "Role of technology in promoting sustainable living",
  "The significance of cultural rituals",
  "Impacts of renewable energy on transportation",
  "Benefits of learning about indigenous cultures",
  "Importance of cross-cultural teamwork",
  "Effects of deforestation on indigenous rights",
  "Influence of media on cultural understanding",
  "Role of technology in promoting equality",
  "The concept of cultural appropriation",
  "Impacts of noise pollution on marine ecosystems",
  "Benefits of intercultural art collaborations",
  "Importance of cultural awareness in travel",
  "Effects of air pollution on wildlife conservation",
  "Influence of social media on body image perception",
  "Role of music in promoting intercultural harmony",
  "The significance of cultural diversity in music",
  "Impacts of sustainable architecture",
  "Benefits of intercultural learning experiences",
  "Importance of cultural competence in counseling",
  "Effects of water pollution on human health",
  "Influence of advertising on children's behavior",
  "Role of technology in promoting cultural understanding",
  "The concept of cultural pluralism",
  "Impacts of noise pollution on mental well-being",
  "Benefits of cross-cultural collaborations in business",
  "Importance of cultural awareness in marketing",
  "Effects of deforestation on climate patterns",
  "Influence of media on cultural stereotypes",
  "Role of technology in promoting environmental sustainability",
  "The significance of cultural diversity in literature",
  "Impacts of renewable energy on social development",
  "Benefits of studying different art forms",
  "Importance of cross-cultural communication in international relations",
  "Effects of air pollution on human productivity",
  "Influence of social media on cultural exchange",
  "Role of music in promoting peace",
  "The concept of cultural adaptation",
  "Impacts of noise pollution on wildlife conservation",
  "Benefits of intercultural understanding in diplomacy",
  "Importance of cultural sensitivity in customer service",
  "Effects of water scarcity on economic development",
  "Influence of advertising on gender roles",
  "Role of technology in promoting cross-cultural interactions",
  "The significance of cultural diversity in film",
  "Impacts of sustainable farming practices",
  "Benefits of intercultural culinary experiences",
  "Importance of cultural empathy in healthcare",
  "Effects of deforestation on indigenous knowledge",
  "Influence of media on cultural assimilation",
  "Role of technology in promoting cultural preservation",
  "The concept of cultural relativity",
  "Impacts of noise pollution on urban wildlife",
  "Benefits of cross-cultural understanding in education",
  "Importance of cultural competency in social work",
  "Effects of air pollution on public health",
  "Influence of social media on cross-cultural friendships",
  "Role of music in promoting intercultural dialogue",
  "The significance of cultural diversity in theater",
  "Impacts of renewable energy on rural development",
  "Benefits of learning about world cultures",
  "Importance of cross-cultural collaboration in research",
  "Effects of water pollution on aquatic life",
  "Influence of advertising on cultural values",
  "Role of technology in preserving endangered languages",
  "The concept of cultural heritage",
  "Impacts of noise pollution on community well-being",
  "Benefits of intercultural exchange programs",
  "Importance of cultural sensitivity in journalism",
  "Effects of deforestation on indigenous cultures",
  "Influence of media on cultural preservation",
  "Role of technology in promoting intercultural awareness",
  "The significance of cultural diversity in architecture",
  "Impacts of sustainable development goals",
  "Benefits of intercultural music collaborations",
  "Importance of cultural understanding in diplomacy",
  "Effects of air pollution on wildlife extinction",
  "Influence of social media on cultural identity",
  "Role of music in promoting cultural acceptance",
  "The concept of cultural revolution",
  "Impacts of noise pollution on public safety",
  "Benefits of cross-cultural experiences in the workplace",
  "Importance of cultural awareness in healthcare settings",
  "Effects of water scarcity on social unrest",
  "Influence of advertising on cultural stereotypes",
  "Role of technology in promoting cultural integration",
  "The significance of cultural diversity in fashion",
  "Impacts of renewable energy on poverty reduction",
  "Benefits of learning about indigenous languages",
  "Importance of cross-cultural understanding in tourism",
  "Effects of deforestation on climate regulation",
  "Influence of media on cultural diversity",
  "Role of technology in fostering intercultural communication",
  "The concept of cultural exchange",
  "Impacts of noise pollution on children's development",
  "Benefits of intercultural storytelling",
  "Importance of cultural competence in education",
  "Effects of air pollution on respiratory diseases",
  "Influence of social media on cultural stereotypes",
  "Role of music in promoting intercultural harmony",
  "The significance of cultural diversity in cuisine",
  "Impacts of renewable energy on sustainable transportation",
  "Benefits of learning about different belief systems",
  "Importance of cross-cultural understanding in journalism",
  "Effects of water pollution on ecosystem health",
  "Influence of advertising on cultural appropriation",
  "Role of technology in preserving cultural heritage",
  "The concept of cultural assimilation",
  "Impacts of noise pollution on mental health",
  "Benefits of intercultural cooperation in science",
  "Importance of cultural awareness in human resources",
  "Effects of deforestation on water availability",
  "Influence of media on cultural understanding",
  "Role of technology in promoting cross-cultural art",
  "The significance of cultural diversity in music festivals",
]